### ISSUE TITLE
Implement QR Code Generator

### ISSUE THREAD

**Issue by thomasarivera** [sus-tainer/sustainer#1]
Please do work in a branch called issue-1.

Create a component that generates a qr code:
- Find a qr code library
- Create a qr code generator component for users
- Create a qr code generator component for containers
- Create a qr code generator component for vendors
- Create a qr code generator component for admin

**Comment by jpinera** [comment]
<img width="1490" alt="qr-code-generator" src="https://github.com/sus-tainer/sustainer/assets/143152443/db5678d3-3818-4050-bcee-54a55f2fab54">
