### ISSUE TITLE
User Sign-Up Forum

### ISSUE THREAD

**Issue by thomasarivera** [sus-tainer/sustainer#11]
Please do work in a branch called issue-5.

Edit the template Sign-Up forum to include a first and last name entry.

**Comment by jpinera** [comment]
<img width="1508" alt="register-page" src="https://github.com/sus-tainer/sustainer/assets/143152443/ee541f50-4010-4d11-87a0-0dd0e0a8e641">

**Comment by jpinera** [comment]
Let me know if there are any comments to improve
