### ISSUE TITLE
Log-In Fourm

### ISSUE THREAD

**Issue by thomasarivera** [sus-tainer/sustainer#12]
Please do work in a branch called issue-6.

Implement current designs to match app aesthetic.

**Comment by jpinera** [comment]
<img width="1508" alt="Login-page" src="https://github.com/sus-tainer/sustainer/assets/143152443/44a727e5-ead5-4231-984f-05d84dd257aa">

**Comment by jpinera** [comment]
Let me know if there are any suggestions to improve
