### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by thomasarivera** [sus-tainer/sustainer#13]
Please do work in a branch called issue-7.

Make a landing page that has the following:

- Title of the app
- Two large buttons that lead to log-in or sign-up
- A short description of what the app does
- make it look pleasing to look at and use

**Comment by jpinera** [comment]
<img width="1498" alt="landing-page" src="https://github.com/sus-tainer/sustainer/assets/143152443/a5037fb7-ad43-4885-adf9-20376f5d125e">

**Comment by jpinera** [comment]
Let me know if there are any changes to implement
